#.github/workflows/java-maven-docker-ci.yml
name: Java CI with Maven and Docker

on:
  # Trigger on pushes to the main branch or any tags starting with 'v'
  push:
    branches: [ main, release-alpha-v1 ]
    tags: [ 'v*' ]
  # Trigger on pull requests opened or updated against the main branch
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main, release-alpha-v1 ]

# Define environment variables for Docker Hub - Use GitHub Variables/Secrets
env:
  DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }} # Store Docker Hub username in GitHub Variables
  # DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }} # Store Docker Hub PAT in GitHub Secrets (used directly in login step)
  IMAGE_NAME: ${{ github.event.repository.name }} # Use repository name as image name (adjust if needed)

jobs:
  build-and-publish:
    runs-on: self-hosted
    # Define permissions for the GITHUB_TOKEN if needed by actions
    permissions:
      contents: read # Needed by checkout
      packages: write # Example: if pushing to GHCR instead/as well
      # id-token: write # Needed for OIDC authentication (e.g., AWS ECR)

    steps:
      - name: Mark Workspace as Safe Directory
        shell: powershell # Use powershell or pwsh
        run: git config --global --add safe.directory $env:GITHUB_WORKSPACE
    
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          # Checkout the head commit for pull requests for accurate testing
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
          fetch-depth: 0 # Fetch all history if needed by build tools (e.g., maven-release-plugin), otherwise default (1) is faster

      - name: Set up JDK 21 and Maven Cache
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven' # Enable Maven dependency caching

      - name: Build with Maven
        # -B runs in batch mode (non-interactive)
        run: mvn -B package --file pom.xml



      - name: Extract Maven project version
        id: get_version # Optional: Give the step an ID if you need the version later
        # Specify PowerShell (pwsh is usually preferred if available)
        # This ensures the correct syntax is expected
        shell: powershell
        run: |
          echo "Reading version directly from pom.xml..."
          try {
              # Define the path to pom.xml (usually at the root after checkout)
              $PomPath = "pom.xml"

              # Check if the file exists
              if (-not (Test-Path $PomPath)) {
                  echo "ERROR: pom.xml not found at $PomPath"
                  exit 1 # Exit with error
              }

              # Read the entire file content and parse it as XML
              # Using -Raw ensures it reads the whole file as one string
              [xml]$PomXml = Get-Content -Path $PomPath -Raw

              # Extract the version string from the parsed XML object
              # $PomXml.project refers to the root <project> element
              $VERSION = $PomXml.project.version

              # Check if version was actually found in the XML structure
              if (-not $VERSION) {
                  echo "ERROR: Could not find project version within pom.xml structure."
                  # Optional: Display part of the parsed XML structure for debugging
                  # echo ($PomXml.project | Format-List *)
                  exit 1 # Exit with error
              }

              # Trim any potential whitespace
              $VERSION = $VERSION.Trim()

              echo "Detected Project Version (from pom.xml): $VERSION"
              # Set the output variable for subsequent steps
              echo "version=$VERSION" >> $env:GITHUB_OUTPUT

          } catch {
              # Catch any errors during file reading or XML parsing
              echo "ERROR: Failed to read or parse pom.xml."
              # Output the specific error caught by PowerShell
              Write-Error $_
              exit 1 # Exit with error
          }

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Use the output 'version' from the 'project' step
          images: ${{ vars.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }} # Example image name
          tags: type=raw,value=${{ env.IMAGE_NAME }}-${{ steps.project.outputs.version }}
            

      - name: Log in to Docker Hub
        # Only log in if pushing (i.e., not a PR event typically, unless pushing directly from PR is desired)
        if: github.event_name!= 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Use the secret directly here

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./ # Use workspace context after checkout and build
          file: ./Dockerfile
          # Push only on pushes to the default branch or tag pushes, not on PRs
          push: ${{ github.event_name!= 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Enable build cache for faster subsequent builds (requires buildx setup)
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
