---
name: Feature to Release CI/CD
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - release/**
    paths:
      - "**"
jobs:
  build_and_test:
    name: Build, Test, and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Echo Test
        run: echo "Workflow started!"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: adoptopenjdk
      - name: Build with Maven
        run: mvn clean package
      - name: Run Unit Tests
        run: mvn test
      - name: Run Static Analysis (SpotBugs)
        run: mvn spotbugs:check
      - name: Build Docker image
        if: github.event_name == 'pull_request'
        run: docker build -t ${{ github.repository }}:${{ github.head_ref }} .
      - name: Save Docker Image Artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-${{ github.head_ref }}
          path: ${{ github.workspace }}/${{ github.repository }}-${{ github.head_ref
            }}.tar
        continue-on-error: true
  publish_to_dockerhub:
    name: Publish to Docker Hub
    needs: build_and_test
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged &&
      github.event.pull_request.base.ref == 'release' &&
      startsWith(github.event.pull_request.head.ref, 'feature/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Docker login
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{
          secrets.DOCKERHUB_TOKEN }}"
      - name: Load Docker Image Artifact
        uses: actions/download-artifact@v3
        with:
          name: docker-image-${{ github.head_ref }}
          path: .
      - name: Load Docker image
        run: docker load --input ${{ github.workspace }}/${{ github.repository }}-${{
          github.head_ref }}.tar
      - name: Tag Docker image
        run: docker tag ${{ github.repository }}:${{ github.head_ref }} ${{
          secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{
          github.event.pull_request.head.ref }}
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{
          github.event.pull_request.head.ref }}
